/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WireTransferRouteImport } from './routes/wire-transfer'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayBillsRouteImport } from './routes/pay-bills'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalTransferRouteImport } from './routes/local-transfer'
import { Route as InternalTransferRouteImport } from './routes/internal-transfer'
import { Route as CryptoDepositRouteImport } from './routes/crypto-deposit'
import { Route as CheckDepositRouteImport } from './routes/check-deposit'
import { Route as CardDepositRouteImport } from './routes/card-deposit'
import { Route as BuyCryptoRouteImport } from './routes/buy-crypto'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddBeneficiaryRouteImport } from './routes/add-beneficiary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersListRouteImport } from './routes/admin/users-list'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProspectiveUsersRouteImport } from './routes/admin/prospective-users'
import { Route as AdminPendingTransactionsRouteImport } from './routes/admin/pending-transactions'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminBeneficiaryRequestsRouteImport } from './routes/admin/beneficiary-requests'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'

const WireTransferRoute = WireTransferRouteImport.update({
  id: '/wire-transfer',
  path: '/wire-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillsRoute = PayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalTransferRoute = LocalTransferRouteImport.update({
  id: '/local-transfer',
  path: '/local-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalTransferRoute = InternalTransferRouteImport.update({
  id: '/internal-transfer',
  path: '/internal-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoDepositRoute = CryptoDepositRouteImport.update({
  id: '/crypto-deposit',
  path: '/crypto-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckDepositRoute = CheckDepositRouteImport.update({
  id: '/check-deposit',
  path: '/check-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CardDepositRoute = CardDepositRouteImport.update({
  id: '/card-deposit',
  path: '/card-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCryptoRoute = BuyCryptoRouteImport.update({
  id: '/buy-crypto',
  path: '/buy-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBeneficiaryRoute = AddBeneficiaryRouteImport.update({
  id: '/add-beneficiary',
  path: '/add-beneficiary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersListRoute = AdminUsersListRouteImport.update({
  id: '/users-list',
  path: '/users-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProspectiveUsersRoute = AdminProspectiveUsersRouteImport.update({
  id: '/prospective-users',
  path: '/prospective-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingTransactionsRoute =
  AdminPendingTransactionsRouteImport.update({
    id: '/pending-transactions',
    path: '/pending-transactions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeneficiaryRequestsRoute =
  AdminBeneficiaryRequestsRouteImport.update({
    id: '/beneficiary-requests',
    path: '/beneficiary-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-beneficiary': typeof AddBeneficiaryRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/card-deposit': typeof CardDepositRoute
  '/check-deposit': typeof CheckDepositRoute
  '/crypto-deposit': typeof CryptoDepositRoute
  '/internal-transfer': typeof InternalTransferRoute
  '/local-transfer': typeof LocalTransferRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pay-bills': typeof PayBillsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/wire-transfer': typeof WireTransferRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beneficiary-requests': typeof AdminBeneficiaryRequestsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pending-transactions': typeof AdminPendingTransactionsRoute
  '/admin/prospective-users': typeof AdminProspectiveUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/users-list': typeof AdminUsersListRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-beneficiary': typeof AddBeneficiaryRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/card-deposit': typeof CardDepositRoute
  '/check-deposit': typeof CheckDepositRoute
  '/crypto-deposit': typeof CryptoDepositRoute
  '/internal-transfer': typeof InternalTransferRoute
  '/local-transfer': typeof LocalTransferRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pay-bills': typeof PayBillsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/wire-transfer': typeof WireTransferRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beneficiary-requests': typeof AdminBeneficiaryRequestsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pending-transactions': typeof AdminPendingTransactionsRoute
  '/admin/prospective-users': typeof AdminProspectiveUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/users-list': typeof AdminUsersListRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-beneficiary': typeof AddBeneficiaryRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/card-deposit': typeof CardDepositRoute
  '/check-deposit': typeof CheckDepositRoute
  '/crypto-deposit': typeof CryptoDepositRoute
  '/internal-transfer': typeof InternalTransferRoute
  '/local-transfer': typeof LocalTransferRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pay-bills': typeof PayBillsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/wire-transfer': typeof WireTransferRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/beneficiary-requests': typeof AdminBeneficiaryRequestsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pending-transactions': typeof AdminPendingTransactionsRoute
  '/admin/prospective-users': typeof AdminProspectiveUsersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/users-list': typeof AdminUsersListRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-beneficiary'
    | '/admin'
    | '/admin-login'
    | '/buy-crypto'
    | '/card-deposit'
    | '/check-deposit'
    | '/crypto-deposit'
    | '/internal-transfer'
    | '/local-transfer'
    | '/login'
    | '/notifications'
    | '/pay-bills'
    | '/profile'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/wire-transfer'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/beneficiary-requests'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/overview'
    | '/admin/pending-transactions'
    | '/admin/prospective-users'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/users-list'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-beneficiary'
    | '/admin'
    | '/admin-login'
    | '/buy-crypto'
    | '/card-deposit'
    | '/check-deposit'
    | '/crypto-deposit'
    | '/internal-transfer'
    | '/local-transfer'
    | '/login'
    | '/notifications'
    | '/pay-bills'
    | '/profile'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/wire-transfer'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/beneficiary-requests'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/overview'
    | '/admin/pending-transactions'
    | '/admin/prospective-users'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/users-list'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/add-beneficiary'
    | '/admin'
    | '/admin-login'
    | '/buy-crypto'
    | '/card-deposit'
    | '/check-deposit'
    | '/crypto-deposit'
    | '/internal-transfer'
    | '/local-transfer'
    | '/login'
    | '/notifications'
    | '/pay-bills'
    | '/profile'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/wire-transfer'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/beneficiary-requests'
    | '/admin/chat'
    | '/admin/notifications'
    | '/admin/overview'
    | '/admin/pending-transactions'
    | '/admin/prospective-users'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/users-list'
    | '/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBeneficiaryRoute: typeof AddBeneficiaryRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BuyCryptoRoute: typeof BuyCryptoRoute
  CardDepositRoute: typeof CardDepositRoute
  CheckDepositRoute: typeof CheckDepositRoute
  CryptoDepositRoute: typeof CryptoDepositRoute
  InternalTransferRoute: typeof InternalTransferRoute
  LocalTransferRoute: typeof LocalTransferRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PayBillsRoute: typeof PayBillsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TransactionsRoute: typeof TransactionsRoute
  WireTransferRoute: typeof WireTransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wire-transfer': {
      id: '/wire-transfer'
      path: '/wire-transfer'
      fullPath: '/wire-transfer'
      preLoaderRoute: typeof WireTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bills': {
      id: '/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof PayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-transfer': {
      id: '/local-transfer'
      path: '/local-transfer'
      fullPath: '/local-transfer'
      preLoaderRoute: typeof LocalTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-transfer': {
      id: '/internal-transfer'
      path: '/internal-transfer'
      fullPath: '/internal-transfer'
      preLoaderRoute: typeof InternalTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-deposit': {
      id: '/crypto-deposit'
      path: '/crypto-deposit'
      fullPath: '/crypto-deposit'
      preLoaderRoute: typeof CryptoDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-deposit': {
      id: '/check-deposit'
      path: '/check-deposit'
      fullPath: '/check-deposit'
      preLoaderRoute: typeof CheckDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-deposit': {
      id: '/card-deposit'
      path: '/card-deposit'
      fullPath: '/card-deposit'
      preLoaderRoute: typeof CardDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-crypto': {
      id: '/buy-crypto'
      path: '/buy-crypto'
      fullPath: '/buy-crypto'
      preLoaderRoute: typeof BuyCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-beneficiary': {
      id: '/add-beneficiary'
      path: '/add-beneficiary'
      fullPath: '/add-beneficiary'
      preLoaderRoute: typeof AddBeneficiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users-list': {
      id: '/admin/users-list'
      path: '/users-list'
      fullPath: '/admin/users-list'
      preLoaderRoute: typeof AdminUsersListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prospective-users': {
      id: '/admin/prospective-users'
      path: '/prospective-users'
      fullPath: '/admin/prospective-users'
      preLoaderRoute: typeof AdminProspectiveUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending-transactions': {
      id: '/admin/pending-transactions'
      path: '/pending-transactions'
      fullPath: '/admin/pending-transactions'
      preLoaderRoute: typeof AdminPendingTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beneficiary-requests': {
      id: '/admin/beneficiary-requests'
      path: '/beneficiary-requests'
      fullPath: '/admin/beneficiary-requests'
      preLoaderRoute: typeof AdminBeneficiaryRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBeneficiaryRequestsRoute: typeof AdminBeneficiaryRequestsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPendingTransactionsRoute: typeof AdminPendingTransactionsRoute
  AdminProspectiveUsersRoute: typeof AdminProspectiveUsersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminUsersListRoute: typeof AdminUsersListRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminBeneficiaryRequestsRoute: AdminBeneficiaryRequestsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPendingTransactionsRoute: AdminPendingTransactionsRoute,
  AdminProspectiveUsersRoute: AdminProspectiveUsersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminUsersListRoute: AdminUsersListRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBeneficiaryRoute: AddBeneficiaryRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BuyCryptoRoute: BuyCryptoRoute,
  CardDepositRoute: CardDepositRoute,
  CheckDepositRoute: CheckDepositRoute,
  CryptoDepositRoute: CryptoDepositRoute,
  InternalTransferRoute: InternalTransferRoute,
  LocalTransferRoute: LocalTransferRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PayBillsRoute: PayBillsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TransactionsRoute: TransactionsRoute,
  WireTransferRoute: WireTransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
